FROM node:alpine

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

ENV URL=mongodb+srv://papyrus123:papyrus123@cluster0.czjsl.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
ENV SECRET_KEY=mynameismahipadhikarifjenfbffsbfvfebgbsegersbgtbgvtbgvtbgk

EXPOSE 5000

CMD [ "npm","start" ]